apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-rqjxrfhb
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/quay_xjiang/go-rqjxrfhb:jenkins-8379a558aac314117631203041570f403e39c85f
          name: container-image
